language: go
script: make build-dev
services:
- docker
before_install: make docker-build
before_deploy: tar -cvzf graphite-writer-stats.tar.gz ./graphite-writer-stats
deploy:
  provider: releases
  api_key:
    secure: "mmBjua/1BcaQHZsQH1oCaauUVMUtfxHTetvabnCMz+diP2tR2GhVKkzlbeo3IXlbx+YOF7X3DXvZZBPWeUzg7HVZsk0ewVZFhFaQkIqdnMu2lWuyAo8cF8Xku7EYaf3HV9XtG3PB1VI3ifTKAfhwMsR0zRy2+uCAAchz11rNAebQo4j/8G8mBZhwI1yRE3910TyYkg7M9DaXotZClD4ppbpNUEZ9tYn3TqJWUeMHAjHIGD6JEbNSL1PLIUhSD4rAQRkVbh5cpdd1/PXHxvpkh6Ipab1TKo/a8fr+NZKXISQ5lu9m2vdySDIjqVWORJdMWqQe2cLFlsVUXO9MoV6jYR4bkdYwyl8gpuQ9Ue1yX9yB69S2wer+P+M9er1LKL8uwj7OyS6BQf+C5B9/2HA201zL8dRCex19Jb03X4n+pSLidqLLu6RgD+0/9/7DdUpIcMy3KvgoHfcBt6EE20tcWOSFJHRrv9+FgudcLyN6XoyX6Wl+k5Ttbh+KMirEfhMLZ/nwf4o4uPnHvc3VAQK02U4xiVoqCNyOHFkI7z/v82aIx0JAJ7pz/LOou/dYxyKf6Lu/PYHHwmpkYzbENGUTCxUNa50CTXKUQv4G8dsPvEKnzNivqMGTCQx6tO4zkeQ7WmmdZoNWk8oBEoKintGsv9wmD/tNFzJzENqQXFaFkUY="
  file: graphite-writer-stats.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: criteo/graphite-writer-stats
